name: Unit Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  unit-tests:
    runs-on: ubuntu-latest-4-cores-gpu
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup CUDA
      uses: Jimver/cuda-toolkit@v0.2.14
      with:
        cuda: '12.4'
        method: 'network'
        
    - name: Verify CUDA installation
      run: |
        nvcc --version
        nvidia-smi
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        
    - name: Create build directory
      run: mkdir -p build
      
    - name: Configure with CMake
      run: |
        cd build
        cmake .. -DCUDA_ARCH=75  # T4 GPU architecture
        
    - name: Build project
      run: |
        cd build
        cmake --build . -j$(nproc)
        
    - name: Run all unit tests
      run: |
        cd build
        ctest --output-on-failure --verbose
        
    - name: Run main test executable
      run: |
        cd build
        ./parrot_tests
        
    - name: Run individual test categories
      run: |
        cd build
        echo "Running basic operations tests..."
        ./test_basic
        echo "Running sorting tests..."
        ./test_sorting
        echo "Running math operations tests..."
        ./test_math
        echo "Running reductions tests..."
        ./test_reductions
        echo "Running scans tests..."
        ./test_scans
        echo "Running array operations tests..."
        ./test_array_ops
        echo "Running advanced operations tests..."
        ./test_advanced
        echo "Running multidimensional tests..."
        ./test_multidim
        echo "Running integration tests..."
        ./test_integration
        echo "Running top10 tests..."
        ./test_top10
        echo "Running fun tests..."
        ./test_fun
